### ISSUE TITLE
Unsolvable seed? 9012011

### ISSUE THREAD

**Issue by fxbx** [LLCoolDave/ALttPEntranceRandomizer#17]
There might be some glitch or trick I'm unfamiliar with, but I'm all but sure the game has access to this region requiring the Magic Hammer.

~~
ALttP Entrance Randomizer Version 0.4.7-dev  -  Seed: 9012011

Logic:                           noglitches
Mode:                            open
Goal:                            ganon
Entrance Shuffle:                full
Filling Algorithm:               vt25
All Locations Accessible:        Yes
Maps and Compasses in Dungeons:  Yes
L\R Quickswap enabled:           No

[ER_noglitches_normal-open-ganon_full-vt25_9012011_Spoiler.txt](https://github.com/LLCoolDave/ALttPEntranceRandomizer/files/1346940/ER_noglitches_normal-open-ganon_full-vt25_9012011_Spoiler.txt)

Hammer is in [cave-050] Mini Moldorm Cave [top right chest]
Archery Game => Mini Moldorm Cave
Archery Game is in the region "South Dark World"
Either the Hammer or Hammer plus Power Glove would be the only way to access this region

**Comment by fxbx** [comment]
Titan's Mitt alone would allow it to be reached also but that isn't accessible yet either.

**Comment by KevinCathcart** [comment]
Nevermind what I posted before does not work.

**Comment by fxbx** [comment]
@KevinCathcart Thanks for the reply and confirming.

**Comment by KevinCathcart** [comment]
By tracing the logic backwards I have determined how to do this. It is rather tricky. I was almost correct before, but I missed a tricky step.

Use aga1 to get eastern dark world. Go like you are heading to the witches hut. Part way there you will find a [screen that blocks you](http://mikesrpgcenter.com/zelda3/maps/darkworld-4-6.html), appearing to requiring either the power glove or the the hammer. But actually it does not block you.

You can jump into the river near the bottom of that screen. Swim up one screen, and you will find a spot where you can return to land. From there, make your way back south to the screen where you jumped into the river. You can then return to the blocking screen, and hookshot over to western dark world. 

From there go to Village of Outcasts, and south of there jump down next to the archery game hut, and you are good-to-go.

**Comment by fxbx** [comment]
@KevinCathcart I should've checked further before reporting. Thanks for confirming. Closing, non-issue.
