### ISSUE TITLE
0.4.5-dev  has Readme.md and VCRUNTIME14.DLL in wrong location

### ISSUE THREAD

**Issue by SageChaozu** [LLCoolDave/ALttPEntranceRandomizer#8]
Everyone was in Jkoper's Twitch channel trying to troubleshoot the issue with the package. Upon further troubleshooting, we found that VCRUNTIME14.DLL which is needed by Python35.dll is located in the LIB folder. This file should be in ROOT since this is where we had to copy it to get it working. I took another look at the LIB directory to find Readme.md there. I'm thinking you probably want that in ROOT as well.

**Comment by LLCoolDave** [comment]
Fixed for 0.4.6-dev release, also reuploaded 0.4.5-dev with the fixes.
